### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by antares2001** [gehaxelt/Bash-INWX-DynDNS#12]
Hello,

where do I obtain an "ID" for the A / AAAA entry of my domain? In the INWX interface I see no id beside the domain name.

Perhaps you can provide an example / guide?

Thanks

**Comment by joker234** [comment]
I think the IDs are the numbers at the end of the `<div class="record_row" id="record_div_YOURID" …>` Element-ID in your inwx nameserver web interface. You may view these by using the inspector of your favorite browser.
https://developers.google.com/web/tools/chrome-devtools/inspect-styles/
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector

Otherwise you can use the inwx API to get the IDs.
https://www.inwx.de/de/help/apidoc/f/ch02s09.html#nameserver.info

No warranty on this information. It's been a while since I got these IDs.

**Comment by gehaxelt** [comment]
Hi,

thanks @joker234 for quickly answering this. 

I'm  a bit surprised that I didn't describe how to get the IDs in the readme. I'll put that on my todo and update it soon, hopefully. 

Here's a screenshot of the developer tools/inspector on the nameserver page. So yeah as @joker234 described, the ID is the last part of the `record_div_XXXXXXX` attribute value. 

![](http://technik.blogbasis.net/wp-content/uploads/sites/3/2013/07/DNSID_inwx.png)

**Comment by gehaxelt** [comment]
I've updated the readme: 69ce20c]

**Comment by antares2001** [comment]
Thanks a lot!
