### ISSUE TITLE
on error updating ipv4 address it does not retry again

### ISSUE THREAD

**Issue by Strubbl** [gehaxelt/Bash-INWX-DynDNS#15]
I run the dnsupdate.sh as cronjob every 5 minutes. This week updating my ip address at inwx went wrong one night. Although it failed updating my DNS, it did not try again on a later scheduled run of the dnsupdate.sh script. Therefore my DNS was not updated until the next day when my IP address changed again.

The error log message was:

`Di 5. Sep 02:17:11 UTC 2017 | Something went wrong updating the IPv4 address. Check the configuration and make sure you're not using Two-Factor-Authentication.`

I would expect that the dnsupdate.sh tries to update the DNS again if it failed before. Is there some mechanism to force that behaviour?

**Comment by ChristianKrausse** [comment]
I had the same update problem, but in my case, in the last days the cron job did its job correctly. I had multiple update problems but mostly at the second try it worked. But since yesterday there where only unsuccessful entries. My Pullrequest should fix the problems. (maybe the nnev.de could be removed in the pool files, but the domain nnev.de is still registered an possibly only temporarly down)

**Comment by gehaxelt** [comment]
I merged @ChristianKrausse's PR #17
